### PR TITLE
ClassCastException fix for LAN games

### PR DESCRIPTION
**Pull request by dagobertdu94-YT**
This change will fix the ClassCastException that was caused by the unchecked cast from PlayerEntity to ServerPlayerEntity which resulted in LAN games to a crash on the server side.

### CODE REVIEW

**Review by BlueZeeKing — CHANGES_REQUESTED** [review]
`SoundManager` is doesn't import `PlayerEntity` which results in an error

**Review by BlueZeeKing — CHANGES_REQUESTED** [review]
The import for `ServerPlayerEntity` is no longer used and should probably be removed

**Review by BlueZeeKing — CHANGES_REQUESTED** [review]
The indent size in line 37 of `SoundManager` changed for some reason and should be changed back

**Comment by BlueZeeKing** [comment]
Most of these are simple changes and if you enable maintainer commits I could fix them for you

**Comment by dagobertdu94-YT** [comment]
> `SoundManager` is doesn't import `PlayerEntity` which results in an error

I am sorry, I forgot to copy the whole file.
I am new to Github, I don't know how to sync my files from Eclipse to Github.
I will add the missing import and remove the unused import.

**Comment by dagobertdu94-YT** [comment]
Sorry for my mistakes, I haven't found out yet how to sync between Eclipse and GitHub.
But I think it should work now.

**Comment by BlueZeeKing** [comment]
> I am new to Github, I don't know how to sync my files from Eclipse to Github.

No worries, thanks for the PR!

**Review by BlueZeeKing — APPROVED** [review]

**Comment by BlueZeeKing** [comment]
The formatting thing is being weird so I'm going to go ahead and merge then fix the formatting

**Pull request merged**
