### PR TITLE
Placeholders API Support (and preparation for the per-player patch)

### PR DESCRIPTION
**Pull request by CamperSamu**
This PR adds support for [Patbox/TextPlaceholderAPI](https://github.com/Patbox/TextPlaceholderAPI) and adds 5 methods that will be used for a (still W.I.P.) per-player power and permission-based power patch.
If you don't want them I can just refactor the code and add back everything once the other patch is ready.

image

Placeholders added:
- %factions:name%
- %factions:description%
- %factions:state%
- %factions:power%
- %factions:power_formatted%
- %factions:max_power%
- %factions:player_power%
- %factions:player_max_power%
- %factions:required_power%
- %factions:required_power_formatted%

I'm also starting to work on a fork of this mod over at [CampHQmc/factions](https://github.com/CampHQmc/factions) where I will introduce more breaking and radical changes.

### CODE REVIEW

**Comment by CamperSamu** [comment]
Also ignore the Italian lol

**Comment by BlueZeeKing** [comment]
The Placeholder API looks good, but I would like to keep all per-player power stuff separate.

**Review by BlueZeeKing — CHANGES_REQUESTED** [review]
Please remove the per-player power, as it's not done yet

**Comment by CamperSamu** [comment]
Will be done tomorrow, right now I'm not at home and I'll be back late.

**Comment by ickerio** [comment]
Yeah this looks really good. The Placeholder API is awesome. I agree with @BlueZeeKing, probably best to remove the per player stuff until its done. Cheers!

**Comment by CamperSamu** [comment]
The only thing I'd like to keep from the extra methods is `Factions#calculateMaxPower`, so there's a standardized method to calculate a faction's power instead of copy-pasting the same formula over and over.

**Comment by BlueZeeKing** [comment]
> The only thing I'd like to keep from the extra methods is Factions#calculateMaxPower, so there's a standardized method to calculate a faction's power instead of copy-pasting the same formula over and over.

I 100% agree with this. When I reworked part of the config I had to change this in every single place when it could have just been one function.

**Review by CamperSamu — COMMENTED** [review]
Resolved with 868e9a1a5e6b6fea7d66915f44a3560f72ee7a22

**Comment by CamperSamu** [comment]
I need to make the commit respect the config changes, working on it

**Comment by CamperSamu** [comment]
Now everything works with 66dcf3bc0cc6fbcbcc09f3168e44c89846950f5d and CI is passing, waiting on review and merge.

**Review by BlueZeeKing — APPROVED** [review]
The Placeholder API is required while ideally, it would be optional. I could quickly fix this though and isn't that big of an issue

**Comment by CamperSamu** [comment]
> The Placeholder API is required while ideally, it would be optional. I could quickly fix this though and isn't that big of an issue

PAPI is JIJ-able, so it's fine like this, but if you want to change it to modCompile it's just a if statement in the mod init.

**Pull request merged**
