### PR TITLE
Add a f map command to show claimed chunks around you

### LINKED ISSUE #13: Chat based chunk map
### Is your feature request related to a problem?

No issue here, but a suggestion to improving the efficiency of chunk claiming.

### Describe the solution you'd like.

When a command such as `/f claim map` is issued, it would show square cubes colored differently to what land is claimed. It is difficult to explain so I will provide an image at the end of the issue displaying how another faction plugin did it.

### Describe alternatives you've considered.

This could display who's claimed land it is, but that could be unbalanced.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

### Other

image
A screenshot of a spigot factions plugin had a claim map.

### PR DESCRIPTION
**Pull request by KalleStruik**
# Changes
- Add a `/f map` command that shows a 11x13 of chunks around you in chat.

# Screenshot
image

Fixes #13

### CODE REVIEW

**Comment by GoodPro712** [comment]
Looks like this only has support for 2 factions? What if there are more than 2 in the shown space?

**Comment by KalleStruik** [comment]
In its current state it mimics the behaviour of the bukkit plugin of the same name. That being displaying all other factions as one. This should however be easy to change to using the factions colour with a tooltip if that is prefered.

**Comment by GoodPro712** [comment]
Oh right. My bad. I guess it's best to wait for ickerio's opinion on it.

**Comment by LiamBogur** [comment]
I'll probably work on some slight changes to this pull and then either submit my own, or submit a pull request to this pull request.

**Comment by ickerio** [comment]
Hi thanks for another great PR. I'm not going to merge it just yet as I know @LiamBogur and I discussed some changes to this PR they were willing to implement. We discussed changing it to an ongoing radar that turns off chat and keeps pinging every few seconds rather than just one chat message.

Once again, thanks for your contributions.

**Comment by BlueZeeKing** [comment]
Would it be possible to make the colors of other factions the color of the factions? And include that color in the key?

**Comment by KalleStruik** [comment]
Screenshot_20220314_211053
I made it use the faction color. I also added a tooltip with the name of the other faction.

**Comment by BlueZeeKing** [comment]
Would it be possible to also add the name of the faction and its color to the key on the right?

**Comment by KalleStruik** [comment]
Screenshot_20220314_222735
Added them to the key.

**Comment by BlueZeeKing** [comment]
I am going to merge this into a separate branch to tweak some small things, but other than that this looks really good!

**Pull request merged**
