### PR TITLE
Added allies, based on BurgBoi's fork

### PR DESCRIPTION
**Pull request by BlueZeeKing**
Switched rank to use ENUM instead of VARCHAR

### CODE REVIEW

**Comment by BlueZeeKing** [comment]
I also added more power to admin bypass by allowing them to remove claims from any factions

**Comment by LFC6times** [comment]
Hey, is it possible to only add the other team as an ally once they click the accept message? Currently, it adds the target team as an ally on your faction's end regardless of accepting.

**Comment by BlueZeeKing** [comment]
> Hey, is it possible to only add the other team as an ally once they click the accept message? Currently, it adds the target team as an ally on your faction's end regardless of accepting.

I created a new branch with this code added but I haven't been able to test at all yet.

**Comment by Cadenm3ow** [comment]
Soo, can I download the build artifact please?

**Comment by Cadenm3ow** [comment]
Can you give me instructions on how to do that please?

**Comment by BlueZeeKing** [comment]
1. download the src
2. using command line or terminal run gradlew build or ./gradlew build for mac
4. go to the build/libs folder and use the jar that doesn't end in dev or resources

I would recommend you just download the release from the fork though

**Pull request merged**
